$wallpaper = /var/tmp/hypr-rising.jpg

general {
    hide_cursor = true
}

background {
    monitor =
    path = $wallpaper
    blur_passes = 0
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = rgba(255, 255, 255, 0.25)
    check_color = rgba(120, 220, 140, 0.95)
    fail_color = rgba(255, 90, 90, 0.95)
    font_color = rgba(255, 255, 255, 0.95)
    fade_on_empty = false
    rounding = 12
    position = 0, -20
    halign = center
    valign = center
}